apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    repoURL: http://localhost:8889/root/ltheveni/iot-ltheveni.git
    targetRevision: HEAD
    path: manifests
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
