Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Server
  config.vm.define "ltheveniS" do |server|
    server.vm.hostname = "ltheveniS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "ltheveniS"
      vb.memory = 512
      vb.cpus = 1
    end

    server.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | sh -
    SHELL
  end

  # Worker
  config.vm.define "ltheveniSW" do |worker|
    worker.vm.hostname = "ltheveniSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "ltheveniSW"
      vb.memory = 512
      vb.cpus = 1
    end
  end
end
