Vagrant.configure("2") do |config|
  host_os = RbConfig::CONFIG['host_os']
  host_cpu = RbConfig::CONFIG['host_cpu']

  if host_os =~ /darwin/ && host_cpu == "arm64"
    box = "bento/ubuntu-22.04"
  else
    box = "ubuntu/jammy64"
  end
  provider = "virtualbox"
  puts "🛠️  Vagrant is using provider: #{provider}, with box: #{box}"

  config.vm.box = box

  # Server
  config.vm.define "ltheveniS" do |server|
    server.vm.hostname = "ltheveniS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider provider do |vb|
      vb.name = "ltheveniS"
      vb.memory = 1024
      vb.cpus = 1
    end
    server.vm.provision "shell", path: "./scripts/server.sh"
  end

  # Worker
  config.vm.define "ltheveniSW" do |worker|
    worker.vm.hostname = "ltheveniSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider provider do |vb|
      vb.name = "ltheveniSW"
      vb.memory = 1024
      vb.cpus = 1
    end
    worker.vm.provision "shell", path: "./scripts/worker.sh"
  end
end
