apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: iot:apps/Deployment:dev/wil-playground
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"iot:apps/Deployment:dev/wil-playground"},"labels":{"app":"wil-playground"},"name":"wil-playground","namespace":"dev"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"wil-playground"}},"template":{"metadata":{"labels":{"app":"wil-playground"}},"spec":{"containers":[{"image":"wil42/playground:v1","name":"wil-playground","ports":[{"containerPort":8888}]}]}}}}
  creationTimestamp: "2025-07-18T11:46:20Z"
  generation: 1
  labels:
    app: wil-playground
  name: wil-playground
  namespace: dev
  resourceVersion: "1072"
  uid: 90c6999b-5c28-4156-ae17-2c49e4a9fda4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wil-playground
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wil-playground
    spec:
      containers:
      - image: wil42/playground:v1
        imagePullPolicy: IfNotPresent
        name: wil-playground
        ports:
        - containerPort: 8888
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-07-18T11:46:27Z"
    lastUpdateTime: "2025-07-18T11:46:27Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-18T11:46:20Z"
    lastUpdateTime: "2025-07-18T11:46:27Z"
    message: ReplicaSet "wil-playground-74bff75c67" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
